---

- hosts: all
  become: true
  tasks:

  - name: Update repository cache
    ansible.builtin.dnf:
      update_cache: true

  - name: Install the latest version of Apache
    ansible.builtin.dnf:
      name: httpd
      state: latest
