---

- hosts: all
  become: true
  tasks:

  - name: Install the latest versions of nmap and Apache packages; also update repository cache
    ansible.builtin.package:
      name: 
        - "{{ nmap_package }}"
        - "{{ apache_package }}"
      state: latest
      update_cache: true
