---

- hosts: all
  become: true
  tasks:

  - name: Remove nmap and Apache packages
    ansible.builtin.dnf:
      name: 
        - nmap
        - httpd
        - mariadb-server
      state: absent
      autoremove: yes
