---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates on RedHat or CentOS servers
    tags: always
    ansible.builtin.dnf:
      update_cache: true
    when: ansible_distribution in [ "RedHat", "CentOS" ]


- hosts: web_servers
  become: true
  tasks:

  - name: Install latest Apache web server
    tags: apache,redhat
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: Copy default html file on remote web server host
    tags: apache,redhat
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'


- hosts: db_servers
  become: true
  tasks:

  - name: Install latest Maria DB Server
    tags: db,redhat
    ansible.builtin.dnf:
      name: mariadb-server
      state: latest

